// Generated by tools/acp-catalogue.py from the Agent Client Protocol
// registry at https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json.
// Registry version 1.0.0, 6 agents kept of 35. Do not edit by hand — re-run
// the script.

import Foundation

/// The agents from the registry this app is willing to launch.
///
/// Data only — `AgentCatalogue.swift` holds the type and the reasoning, and
/// `tools/acp-catalogue.py` holds the rules about what is left out.
extension AgentCatalogue {

    static let all: [CatalogueAgent] = [
        CatalogueAgent(
            id: "gemini",
            name: "Gemini CLI",
            handle: "gemini",
            blurb: "Google's official CLI for Gemini",
            command: "npx",
            arguments: ["--no-install", "@google/gemini-cli", "--acp"],
            isNode: true,
            environment: [:],
            site: "npm i -g @google/gemini-cli"),
        CatalogueAgent(
            id: "codex-acp",
            name: "Codex",
            handle: "codex",
            blurb: "ACP adapter for OpenAI's coding assistant",
            command: "npx",
            arguments: ["--no-install", "@agentclientprotocol/codex-acp"],
            isNode: true,
            environment: [:],
            site: "npm i -g @agentclientprotocol/codex-acp"),
        CatalogueAgent(
            id: "cursor",
            name: "Cursor",
            handle: "cursor",
            blurb: "Cursor's coding agent",
            command: "cursor-agent",
            arguments: ["acp"],
            isNode: false,
            environment: [:],
            site: "https://cursor.com/docs/cli/acp"),
        CatalogueAgent(
            id: "opencode",
            name: "OpenCode",
            handle: "opencode",
            blurb: "The open source coding agent",
            command: "opencode",
            arguments: ["acp"],
            isNode: false,
            environment: [:],
            site: "https://opencode.ai"),
        CatalogueAgent(
            id: "cline",
            name: "Cline",
            handle: "cline",
            blurb: "Autonomous coding agent CLI - capable of creating/editing files, running commands, using the browser, and more",
            command: "npx",
            arguments: ["--no-install", "cline", "--acp"],
            isNode: true,
            environment: [:],
            site: "npm i -g cline"),
        CatalogueAgent(
            id: "goose",
            name: "goose",
            handle: "goose",
            blurb: "A local, extensible, open source AI agent that automates engineering tasks",
            command: "goose",
            arguments: ["acp"],
            isNode: false,
            environment: [:],
            site: "https://block.github.io/goose/"),
    ]
}
